/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tuning.project.gc;

import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;;

@RestController
public class GCController {
	
	@RequestMapping(value = "/list")
	public void listTest() throws InterruptedException {
		List<Integer> list = IntStream.range(0, 100).boxed().collect(Collectors.toList());
		System.out.println("start");
		for (int i = 0; true; i++) {
			if( i % 100 == 0)
				Thread.sleep(10);
			IntStream.range(0, 100).forEach(list::add);
		}
	}
}
